name: Setup and Build
on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-deploy-develop:
    if: ${{ github.ref == 'refs/heads/develop' }}
    uses: ./.github/workflows/build_and_deploy.yml
    secrets:
      IMAGE: ${{ secrets.IMAGE }}
      GKE_DEPLOYMENT_NAME: ${{ secrets.GKE_DEPLOYMENT_NAME_DEVELOP }}
      GKE_NAMESPACE: ${{ secrets.GKE_NAMESPACE }}
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_TESTNET }}
      GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID_TESTNET }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_TESTNET }}
      GKE_ZONE: ${{ secrets.GKE_ZONE_TESTNET }}

  build-and-deploy-testnet:
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/build_and_deploy.yml
    secrets:
      IMAGE: ${{ secrets.IMAGE }}
      GKE_DEPLOYMENT_NAME: ${{ secrets.GKE_DEPLOYMENT_NAME_TESTNET }}
      GKE_NAMESPACE: ${{ secrets.GKE_NAMESPACE }}
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_TESTNET }}
      GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID_TESTNET }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_TESTNET }}
      GKE_ZONE: ${{ secrets.GKE_ZONE_TESTNET }}
